name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go mod download

      - name: Run linter
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2 && make lint

      - name: Run tests
        run: make test