name: Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest
      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest
            docker stop ${{ secrets.DEPLOY_CONTAINER }} || true
            docker container rm ${{ secrets.DEPLOY_CONTAINER }} || true
            docker run -d --name ${{ secrets.DEPLOY_CONTAINER }} \
              -e TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}\
              -e SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}\
              -e SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}\
              ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest
            echo "Docker prune"
            docker image prune --force --all